apiVersion: v1
kind: Secret
metadata:
  name: {{ include "camunda-backup-controller.fullname" . }}
  labels:
    {{- include "camunda-backup-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.elasticsearch.password }}
  DEFAULT_ELASTICSEARCH_PASSWORD: {{ .Values.secrets.elasticsearch.password | quote }}
  {{- end }}
  {{- if .Values.secrets.s3.accessKey }}
  DEFAULT_S3_ACCESSKEY: {{ .Values.secrets.s3.accessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.s3.secretKey }}
  DEFAULT_S3_SECRETKEY: {{ .Values.secrets.s3.secretKey | quote }}
  {{- end }}
  {{- range $instance, $creds := .Values.secrets.instanceOverrides }}
  {{- $suffix := upper (replace "-" "_" $instance) }}
  {{- if $creds.elasticsearchPassword }}
  ELASTICSEARCH_PASSWORD_{{ $suffix }}: {{ $creds.elasticsearchPassword | quote }}
  {{- end }}
  {{- if $creds.s3SecretKey }}
  S3_SECRETKEY_{{ $suffix }}: {{ $creds.s3SecretKey | quote }}
  {{- end }}
  {{- end }}
